### PR TITLE
UI overhaul

### PR DESCRIPTION
**Pull request by qubist**

### CODE REVIEW

**Comment by qubist** [comment]
Todo:

- [x] Make bag level move according to number of items in bag
- [x] Remove obsolete collapsible-confirm code
- [ ] Fix layout on small screens

**Comment by qubist** [comment]
Closes #35

**Comment by qubist** [comment]
@snapea I requested review of this PR from you! you can go to ~scrabblebag.org~ [scrabblepouch.com](scrabblepouch.com) and test it out, (i updated it on there). Then you can approve the changes or request tweaks

**Review by poppynorthing — APPROVED** [review]
:D

**Pull request merged**
